apiVersion: v1
kind: PersistentVolume
metadata:
   name: mongodb-pv # Name of the persistent volume
spec:
  storageClassName: local-storage # Name of the storage class
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi # Amount of storage this volume should hold
  accessModes:
    - ReadWriteOnce # To be read and written only once
  local:
    path: /data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube